### PR TITLE
LRAC-9296

### PR DESCRIPTION
**Pull request by alessandromalves**

### CODE REVIEW

**Comment by alessandromalves** [comment]
ci:test:analitycs-cloud:nocompile

**Comment by alessandromalves** [comment]
ci:test:analytics-cloud:nocompile

**Comment by alessandromalves** [comment]
ci:test:analitycs-cloud

**Comment by alessandromalves** [comment]
ci:test:analytics-cloud:nocompile

**Comment by alessandromalves** [comment]
ci:test:analytics-cloud

**Comment by alessandromalves** [comment]
ci:test:analytics-cloud:nocompile

**Comment by alessandromalves** [comment]
ci:test:analytics-cloud:nocompile

**Comment by alessandromalves** [comment]
ci:test:analytics-cloud:nocompile

**Comment by alessandromalves** [comment]
ci:test:analytics-cloud:nocompile

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud:nocompile

**Comment by alessandromalves** [comment]
ci:test:analytics-cloud:nocompile

**Pull request closed without merging**
