### PR TITLE
LRQA-76041 | master

### PR DESCRIPTION
**Pull request by alessandromalves**
https://issues.liferay.com/browse/LRQA-76041

### CODE REVIEW

**Comment by alessandromalves** [comment]
ci:test:sf

**Comment by alessandromalves** [comment]
ci:test:sf

**Comment by alessandromalves** [comment]
ci:forward

**Comment by alessandromalves** [comment]
ci:forward

**Comment by alessandromalves** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:close

**Pull request merged**
