### PR TITLE
LPS-156447, LPS-156459 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LPS-156447
https://issues.liferay.com/browse/LPS-156459
@diogocordeiro

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:forms-functional

**Comment by alessandromalves** [comment]
LPS-156447 resent [here](https://github.com/alessandromalves/liferay-portal/pull/18)

**Comment by alessandromalves** [comment]
LPS-156459 resent [Here](https://github.com/alessandromalves/liferay-portal/pull/24)

**Pull request closed without merging**
